#!/usr/bin/env python
"""
Prints paths of identical files to stdout, separated by tab (\t).

How it works
------------
The script calculates the MD5 checksums of all the files of the same size
underneath the base path I use as my argument. If these MD5s match, the path
is printed.

How to use it
-------------
### List identical pictures in my album.
    $ ./repeats ~/album
        ~/album/_import/IMG_0034.JPG	~/album/my-trip/IMG_0034.JPG
"""
import hashlib
import os
import os.path
import sys
from collections import defaultdict


DELIMINATOR = "\t"


def main(where):
    for line in repeats(where):
        print(line)


def repeats(where):
    limiters = [by_size, by_md5]
    all_files = list(get_all_files(where))
    groups = [all_files]
    groups = by_size(groups)
    groups = by_md5(groups)
    matches = groups
    for same_list in matches:
        yield(DELIMINATOR.join(same_list))


def get_all_files(where):
    filerecords = os.walk(where)
    for dirpath, dirnames, filenames in filerecords:
        for name in filenames:
            yield os.path.join(dirpath, name)


def by_size(candidates):
    return apply_limiter(candidates, os.path.getsize)


def by_md5(candidates):
    return apply_limiter(candidates, calculate_md5)


def calculate_md5(path):
    """
    Returns the MD5 hash for a file at ``path``.
    """
    md5 = hashlib.md5()
    with open(path) as openfile:
        while True:
            buf = openfile.read(128)
            if not buf:
                break
            md5.update(buf)
    return md5.hexdigest()


def apply_limiter(groups_of_possible_matches, limiter):
    results = []
    for possible_match in groups_of_possible_matches:
        new_elements = group_by(possible_match, limiter).values()
        for element in new_elements:
            if len(element) > 1:
                results.append(element)
    return results


def group_by(iterable, keyfunc):
    groups = defaultdict(list)
    for iterated in iterable:
        result = keyfunc(iterated)
        groups[result].append(iterated)
    return groups


if __name__ == "__main__":
    try:
        where = sys.argv[1]
    except IndexError:
        where = "./"
    main(where)
